name: Trigger CRM Sync Job

on:
  schedule:
    - cron: "*/5 * * * *"  # Every 5 minutes
  workflow_dispatch:       # Allow manual trigger from UI

jobs:
  ping-crm-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Call CRM Sync Route
        run: |
          curl -X GET https://thelevelupagency.com/api/crm-sync-job \
            -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}"
